import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-retail-slotting-scanback-allowance-recovery",
  "engine": "recovery",
  "title": "Retail Slotting & Scan-Back Allowance Recovery",
  "shortTitle": "Retail Slotting and Scan-Back Allowance Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through retail slotting & scan-back allowance recovery",
  "industry": "Retail Channel Allowance Recovery",
  "uiPort": 4620,
  "apiPort": 5620,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Retail Slotting & Scan-Back Allowance Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedAllowance",
    "expectedKey": "earnedAllowance",
    "actualLabel": "Received Allowance",
    "expectedLabel": "Calculated Earned Allowance",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Retail Slotting & Scan-Back Allowance Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("retailer-program-library","RSS01","Retailer program library","Execute retailer program library using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed retailer program library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Retailer program library Reference","text","RSS01-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("store-sku-registry","RSS02","Store SKU registry","Execute store sku registry using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed store sku registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Store SKU registry Reference","text","RSS02-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("slotting-commitment-tracking","RSS03","Slotting commitment tracking","Execute slotting commitment tracking using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed slotting commitment tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Slotting commitment tracking Reference","text","RSS03-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("new-store-authorization","RSS04","New-store authorization","Execute new-store authorization using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed new-store authorization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","New-store authorization Reference","text","RSS04-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("pos-scan-ingestion","RSS05","POS scan ingestion","Execute pos scan ingestion using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed pos scan ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","POS scan ingestion Reference","text","RSS05-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("scan-back-calculation","RSS06","Scan-back calculation","Execute scan-back calculation using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed scan-back calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Scan-back calculation Reference","text","RSS06-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("display-placement-evidence","RSS07","Display placement evidence","Execute display placement evidence using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed display placement evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Display placement evidence Reference","text","RSS07-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("advertising-compliance","RSS08","Advertising compliance","Execute advertising compliance using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed advertising compliance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Advertising compliance Reference","text","RSS08-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("proof-of-performance-collection","RSS09","Proof-of-performance collection","Execute proof-of-performance collection using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed proof-of-performance collection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Proof-of-performance collection Reference","text","RSS09-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("deduction-matching","RSS10","Deduction matching","Execute deduction matching using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed deduction matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Deduction matching Reference","text","RSS10-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("earned-allowance-calculation","RSS11","Earned allowance calculation","Execute earned allowance calculation using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed earned allowance calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Earned allowance calculation Reference","text","RSS11-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("supplier-claim-package","RSS12","Supplier claim package","Execute supplier claim package using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed supplier claim package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Supplier claim package Reference","text","RSS12-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("supplier-response-workflow","RSS13","Supplier response workflow","Execute supplier response workflow using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed supplier response workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Supplier response workflow Reference","text","RSS13-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("cash-credit-reconciliation","RSS14","Cash credit reconciliation","Execute cash credit reconciliation using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed cash credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Cash credit reconciliation Reference","text","RSS14-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]}),
feature("store-sku-program-analytics","RSS15","Store SKU program analytics","Execute store sku program analytics using retailer programs, stores, SKUs, slotting commitments, POS scans, displays, placements, advertising, proof of performance, deductions, claims, and payments.","Produce a governed store sku program analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Supplier Program","text","Retailer / Supplier Program · Standard Case"],["caseReference","Store SKU program analytics Reference","text","RSS15-2026-001"],["receivedAllowance","Received Allowance","currency",956500],["earnedAllowance","Calculated Earned Allowance","currency",1128670],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedAllowance",subjects:["Retailer program library case","Store SKU registry case","Slotting commitment tracking case","New-store authorization case","POS scan ingestion case"]})
]);
